"""Add email field to users

Revision ID: 4da2db09358b
Revises: d0502358eafe
Create Date: 2026-06-22 17:04:32.793995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da2db09358b'
down_revision: Union[str, Sequence[str], None] = 'd0502358eafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bronze_releves_incidents', sa.Column('valid_error_reason', sa.Text(), nullable=True))
    op.alter_column('bronze_releves_incidents', 'incident_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bronze_releves_incidents', 'valid_parsing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('bronze_telemetry', sa.Column('valid_error_reason', sa.Text(), nullable=True))
    op.alter_column('bronze_telemetry', 'machine_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bronze_telemetry', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bronze_telemetry', 'valid_parsing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bronze_telemetry', 'valid_parsing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bronze_telemetry', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bronze_telemetry', 'machine_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('bronze_telemetry', 'valid_error_reason')
    op.alter_column('bronze_releves_incidents', 'valid_parsing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bronze_releves_incidents', 'incident_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('bronze_releves_incidents', 'valid_error_reason')
    # ### end Alembic commands ###
