"""add per-machine zscore features to gold_telemetry

Revision ID: 5a6f1c1b9c0c
Revises: c9e10bb1b84e
Create Date: 2026-07-05 15:22:58.393742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6f1c1b9c0c'
down_revision: Union[str, Sequence[str], None] = 'c9e10bb1b84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_telemetry', sa.Column('temperature_zscore_machine', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_zscore_machine', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_zscore_machine', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_zscore_machine', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gold_telemetry', 'rotation_zscore_machine')
    op.drop_column('gold_telemetry', 'voltage_zscore_machine')
    op.drop_column('gold_telemetry', 'pressure_zscore_machine')
    op.drop_column('gold_telemetry', 'temperature_zscore_machine')
    # ### end Alembic commands ###
