"""add failure labels to gold_telemetry

Revision ID: 5e752fcb82e8
Revises: 5a6f1c1b9c0c
Create Date: 2026-07-05 15:26:46.068448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e752fcb82e8'
down_revision: Union[str, Sequence[str], None] = '5a6f1c1b9c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_telemetry', sa.Column('label_failure_next_6h', sa.Boolean(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('label_failure_next_12h', sa.Boolean(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('label_failure_next_24h', sa.Boolean(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('label_failure_next_48h', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gold_telemetry', 'label_failure_next_48h')
    op.drop_column('gold_telemetry', 'label_failure_next_24h')
    op.drop_column('gold_telemetry', 'label_failure_next_12h')
    op.drop_column('gold_telemetry', 'label_failure_next_6h')
    # ### end Alembic commands ###
