"""Add batch table

Revision ID: 6768ee89fb15
Revises: 4da2db09358b
Create Date: 2026-06-22 17:50:00.834298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6768ee89fb15'
down_revision: Union[str, Sequence[str], None] = '4da2db09358b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bronze_batch')
    # ### end Alembic commands ###
