"""add gold tables

Revision ID: 6bcdaf594cc1
Revises: d7a6c78d8bd4
Create Date: 2026-07-05 14:32:09.362570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcdaf594cc1'
down_revision: Union[str, Sequence[str], None] = 'd7a6c78d8bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_machine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=True),
    sa.Column('max_daily_capacity', sa.Integer(), nullable=True),
    sa.Column('max_hourly_capacity_pieces', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=True),
    sa.Column('production_line', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=16), nullable=True),
    sa.Column('criticality', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_maintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=16), nullable=True),
    sa.Column('maintenance_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=16), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_incident_id', sa.String(length=16), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_releves_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Text(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('operator_name', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.BigInteger(), nullable=True),
    sa.Column('operator_badge', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('shift', sa.Text(), nullable=True),
    sa.Column('type_surchauffe', sa.BigInteger(), nullable=True),
    sa.Column('type_baisse_pression', sa.BigInteger(), nullable=True),
    sa.Column('type_vibration', sa.BigInteger(), nullable=True),
    sa.Column('type_bruit_mecanique', sa.BigInteger(), nullable=True),
    sa.Column('type_surconsommation', sa.BigInteger(), nullable=True),
    sa.Column('type_blocage_mecanique', sa.BigInteger(), nullable=True),
    sa.Column('type_alarme_capteur', sa.BigInteger(), nullable=True),
    sa.Column('type_arret_urgence', sa.BigInteger(), nullable=True),
    sa.Column('type_defaut_qualite', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Text(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pressure_bar', sa.Float(), nullable=True),
    sa.Column('voltage_mean_v', sa.Float(), nullable=True),
    sa.Column('rotation_mean_rpm', sa.Float(), nullable=True),
    sa.Column('pieces_produced', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_telemetry')
    op.drop_table('gold_releves_incidents')
    op.drop_table('gold_maintenance')
    op.drop_table('gold_machine')
    # ### end Alembic commands ###
