"""add rolling window stats to gold_telemetry

Revision ID: b6ec5e50c1c3
Revises: 6bcdaf594cc1
Create Date: 2026-07-05 14:34:10.252619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ec5e50c1c3'
down_revision: Union[str, Sequence[str], None] = '6bcdaf594cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_telemetry', sa.Column('temperature_mean_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_max_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_std_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_mean_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_max_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_std_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_mean_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_max_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_std_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_mean_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_max_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_std_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_mean_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_max_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_std_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_mean_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_max_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('pressure_std_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_mean_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_max_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_std_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_mean_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_max_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_std_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_mean_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_max_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('voltage_std_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_mean_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_max_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_std_6h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_mean_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_max_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_std_12h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_mean_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_max_24h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('rotation_std_24h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gold_telemetry', 'rotation_std_24h')
    op.drop_column('gold_telemetry', 'rotation_max_24h')
    op.drop_column('gold_telemetry', 'rotation_mean_24h')
    op.drop_column('gold_telemetry', 'rotation_std_12h')
    op.drop_column('gold_telemetry', 'rotation_max_12h')
    op.drop_column('gold_telemetry', 'rotation_mean_12h')
    op.drop_column('gold_telemetry', 'rotation_std_6h')
    op.drop_column('gold_telemetry', 'rotation_max_6h')
    op.drop_column('gold_telemetry', 'rotation_mean_6h')
    op.drop_column('gold_telemetry', 'voltage_std_24h')
    op.drop_column('gold_telemetry', 'voltage_max_24h')
    op.drop_column('gold_telemetry', 'voltage_mean_24h')
    op.drop_column('gold_telemetry', 'voltage_std_12h')
    op.drop_column('gold_telemetry', 'voltage_max_12h')
    op.drop_column('gold_telemetry', 'voltage_mean_12h')
    op.drop_column('gold_telemetry', 'voltage_std_6h')
    op.drop_column('gold_telemetry', 'voltage_max_6h')
    op.drop_column('gold_telemetry', 'voltage_mean_6h')
    op.drop_column('gold_telemetry', 'pressure_std_24h')
    op.drop_column('gold_telemetry', 'pressure_max_24h')
    op.drop_column('gold_telemetry', 'pressure_mean_24h')
    op.drop_column('gold_telemetry', 'pressure_std_12h')
    op.drop_column('gold_telemetry', 'pressure_max_12h')
    op.drop_column('gold_telemetry', 'pressure_mean_12h')
    op.drop_column('gold_telemetry', 'pressure_std_6h')
    op.drop_column('gold_telemetry', 'pressure_max_6h')
    op.drop_column('gold_telemetry', 'pressure_mean_6h')
    op.drop_column('gold_telemetry', 'temperature_std_24h')
    op.drop_column('gold_telemetry', 'temperature_max_24h')
    op.drop_column('gold_telemetry', 'temperature_mean_24h')
    op.drop_column('gold_telemetry', 'temperature_std_12h')
    op.drop_column('gold_telemetry', 'temperature_max_12h')
    op.drop_column('gold_telemetry', 'temperature_mean_12h')
    op.drop_column('gold_telemetry', 'temperature_std_6h')
    op.drop_column('gold_telemetry', 'temperature_max_6h')
    op.drop_column('gold_telemetry', 'temperature_mean_6h')
    # ### end Alembic commands ###
