"""add temperature trend features to gold_telemetry

Revision ID: c9e10bb1b84e
Revises: b6ec5e50c1c3
Create Date: 2026-07-05 14:52:04.367981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e10bb1b84e'
down_revision: Union[str, Sequence[str], None] = 'b6ec5e50c1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_telemetry', sa.Column('temperature_trend_1h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_trend_3h', sa.Float(), nullable=True))
    op.add_column('gold_telemetry', sa.Column('temperature_trend_6h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gold_telemetry', 'temperature_trend_6h')
    op.drop_column('gold_telemetry', 'temperature_trend_3h')
    op.drop_column('gold_telemetry', 'temperature_trend_1h')
    # ### end Alembic commands ###
