"""Initial migration

Revision ID: d0502358eafe
Revises: 
Create Date: 2026-06-22 16:01:09.124698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0502358eafe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_machine',
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=True),
    sa.Column('max_daily_capacity', sa.Integer(), nullable=True),
    sa.Column('max_hourly_capacity_pieces', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=True),
    sa.Column('production_line', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=16), nullable=True),
    sa.Column('criticality', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('machine_code')
    )
    op.create_table('bronze_maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=16), nullable=True),
    sa.Column('maintenance_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=16), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_incident_id', sa.String(length=16), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('bronze_releves_incidents',
    sa.Column('incident_id', sa.Text(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('operator_name', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.BigInteger(), nullable=True),
    sa.Column('operator_badge', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('shift', sa.Text(), nullable=True),
    sa.Column('type_surchauffe', sa.BigInteger(), nullable=True),
    sa.Column('type_baisse_pression', sa.BigInteger(), nullable=True),
    sa.Column('type_vibration', sa.BigInteger(), nullable=True),
    sa.Column('type_bruit_mecanique', sa.BigInteger(), nullable=True),
    sa.Column('type_surconsommation', sa.BigInteger(), nullable=True),
    sa.Column('type_blocage_mecanique', sa.BigInteger(), nullable=True),
    sa.Column('type_alarme_capteur', sa.BigInteger(), nullable=True),
    sa.Column('type_arret_urgence', sa.BigInteger(), nullable=True),
    sa.Column('type_defaut_qualite', sa.BigInteger(), nullable=True),
    sa.Column('valid_parsing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('bronze_telemetry',
    sa.Column('machine_id', sa.Text(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pressure_bar', sa.Float(), nullable=True),
    sa.Column('voltage_mean_v', sa.Float(), nullable=True),
    sa.Column('rotation_mean_rpm', sa.Float(), nullable=True),
    sa.Column('pieces_produced', sa.BigInteger(), nullable=True),
    sa.Column('valid_parsing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('machine_id', 'date')
    )
    op.drop_index(op.f('idx_maintenance_machine_time'), table_name='maintenance')
    op.drop_index(op.f('idx_maintenance_type'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('idx_machine_line'), table_name='machine')
    op.drop_index(op.f('idx_machine_location'), table_name='machine')
    op.drop_table('machine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('machine_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('commissioning_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('max_daily_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_hourly_capacity_pieces', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('production_line', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('criticality', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("criticality::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying]::text[])", name=op.f('machine_criticality_check')),
    sa.CheckConstraint('max_daily_capacity > 0', name=op.f('machine_max_daily_capacity_check')),
    sa.CheckConstraint('max_hourly_capacity_pieces > 0', name=op.f('machine_max_hourly_capacity_pieces_check')),
    sa.PrimaryKeyConstraint('machine_code', name=op.f('machine_pkey'))
    )
    op.create_index(op.f('idx_machine_location'), 'machine', ['location'], unique=False)
    op.create_index(op.f('idx_machine_line'), 'machine', ['production_line'], unique=False)
    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('maintenance_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('related_incident_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("maintenance_type::text = ANY (ARRAY['proactive'::character varying, 'reactive'::character varying]::text[])", name=op.f('maintenance_maintenance_type_check')),
    sa.CheckConstraint('duration_hours > 0::numeric', name=op.f('maintenance_duration_hours_check')),
    sa.ForeignKeyConstraint(['machine_code'], ['machine.machine_code'], name=op.f('maintenance_machine_code_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('maintenance_id', name=op.f('maintenance_pkey'))
    )
    op.create_index(op.f('idx_maintenance_type'), 'maintenance', ['maintenance_type'], unique=False)
    op.create_index(op.f('idx_maintenance_machine_time'), 'maintenance', ['machine_code', 'maintenance_at'], unique=False)
    op.drop_table('bronze_telemetry')
    op.drop_table('bronze_releves_incidents')
    op.drop_table('bronze_maintenance')
    op.drop_table('bronze_machine')
    # ### end Alembic commands ###
