"""add silver tables

Revision ID: de63fa565140
Revises: 6768ee89fb15
Create Date: 2026-06-23 11:45:36.970404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de63fa565140'
down_revision: Union[str, Sequence[str], None] = '6768ee89fb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silver_machine',
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=True),
    sa.Column('max_daily_capacity', sa.Integer(), nullable=True),
    sa.Column('max_hourly_capacity_pieces', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=True),
    sa.Column('production_line', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=16), nullable=True),
    sa.Column('criticality', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('machine_code')
    )
    op.create_table('silver_maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=16), nullable=True),
    sa.Column('maintenance_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=16), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_incident_id', sa.String(length=16), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('silver_releves_incidents',
    sa.Column('incident_id', sa.Text(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('operator_name', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.BigInteger(), nullable=True),
    sa.Column('operator_badge', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('shift', sa.Text(), nullable=True),
    sa.Column('type_surchauffe', sa.BigInteger(), nullable=True),
    sa.Column('type_baisse_pression', sa.BigInteger(), nullable=True),
    sa.Column('type_vibration', sa.BigInteger(), nullable=True),
    sa.Column('type_bruit_mecanique', sa.BigInteger(), nullable=True),
    sa.Column('type_surconsommation', sa.BigInteger(), nullable=True),
    sa.Column('type_blocage_mecanique', sa.BigInteger(), nullable=True),
    sa.Column('type_alarme_capteur', sa.BigInteger(), nullable=True),
    sa.Column('type_arret_urgence', sa.BigInteger(), nullable=True),
    sa.Column('type_defaut_qualite', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('silver_telemetry',
    sa.Column('machine_id', sa.Text(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pressure_bar', sa.Float(), nullable=True),
    sa.Column('voltage_mean_v', sa.Float(), nullable=True),
    sa.Column('rotation_mean_rpm', sa.Float(), nullable=True),
    sa.Column('pieces_produced', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('machine_id', 'date')
    )
    op.drop_index(op.f('idx_machine_line'), table_name='bronze_machine')
    op.drop_index(op.f('idx_machine_location'), table_name='bronze_machine')
    op.drop_index(op.f('idx_maintenance_machine_time'), table_name='bronze_maintenance')
    op.drop_index(op.f('idx_maintenance_type'), table_name='bronze_maintenance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_maintenance_type'), 'bronze_maintenance', ['maintenance_type'], unique=False)
    op.create_index(op.f('idx_maintenance_machine_time'), 'bronze_maintenance', ['machine_code', 'maintenance_at'], unique=False)
    op.create_index(op.f('idx_machine_location'), 'bronze_machine', ['location'], unique=False)
    op.create_index(op.f('idx_machine_line'), 'bronze_machine', ['production_line'], unique=False)
    op.drop_table('silver_telemetry')
    op.drop_table('silver_releves_incidents')
    op.drop_table('silver_maintenance')
    op.drop_table('silver_machine')
    # ### end Alembic commands ###
